[package]
name = "cgroup2"
version = "0.0.1"
description = "A library with cgroup2"
authors = ["Eli Ma <eli@patch.sh>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/patchlab/cgroup2.git"
readme = "README.md"

[dependencies]
